
if(NOT DEFINED QT_DIR)
    message(FATAL_ERROR "Variable QT_DIR missing, provide with e.g. -DQT_DIR=C:/qt6/6.1.0/msvc2019_64")
endif()

set(INSTALL_MKSPECSDIR "${QT_DIR}/mkspecs")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6BuildInternals")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6Core")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6CoreTools")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6EntryPoint")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6Gui")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6Network")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6Widgets")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6WidgetsTools")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/lib/cmake/Qt6Xml")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${QT_DIR}/../../Tools/CMake_64/share/cmake-3.19/Modules")
include("FindThreads")
include("FindWrapAtomic")
if (UNIX)
    include("FindWrapOpenGL")
endif()
include("Qt6Targets")
include("Qt6CoreTargets")
include("Qt6CoreVersionlessTargets")
if (WIN32)
    include("Qt6EntryPointTargets")
endif()
include("Qt6GuiTargets")
include("Qt6GuiVersionlessTargets")
include("Qt6NetworkTargets")
include("Qt6NetworkVersionlessTargets")
include("Qt6WidgetsTargets")
include("Qt6WidgetsVersionlessTargets")
include("Qt6WidgetsToolsTargets")
include("Qt6XmlTargets")
include("Qt6XmlVersionlessTargets")
include("Qt6VersionlessTargets")
include("Qt6CoreToolsTargets")
include("QtFeature")
include("Qt6CoreMacros")
include("Qt6BuildInternalsConfig")
include("QtBuild")
include("QtCMakeHelpers")
include("QtExecutableHelpers")